name: Automated Figma To Theme Code

on:
  push:
    paths:
      - "tokens.json"

permissions:
  contents: write

jobs:
  generate-tokens:
    name: Generate Theme Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Prime Theme
        uses: primefaces/theme-designer-ci@1.0.0-beta.4
        with:
          designer-secret: ${{ secrets.THEME_DESIGNER_SECRET_KEY }}
          theme-name: "acme"
          font-size: "14px"
          font-family: "Inter Var"
          project: "primeng"
          tokens-path: "tokens.json"
          output-dir: "./src/app/acme-theme"
