name: Figma To Theme Code

on:
  push:
    paths:
      - "tokens.json"

permissions:
  contents: write

jobs:
  generate-tokens:
    name: Generate Prime Tokens
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Prime Tokens
        uses: primefaces/figma-to-theme-code-generator@1.0.0-beta.3
        with:
          designer-secret: ${{ secrets.THEME_DESIGNER_SECRET_KEY }} # [required] api key for authentication
          theme-name: "acme"
          font-size: "14px"
          font-family: "Inter Var"
          project: "primeng"
          tokens-path: "tokens.json" # [optional] path to tokens file
          output-dir: "./acme-theme" # [optional] output directory
